# Generated by Django 4.2 on 2023-04-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabi', '0007_delete_favorite'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='プロフィール'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='tabi.tabi', verbose_name='お気に入りの場所'),
        ),
    ]
