# Generated by Django 4.2 on 2023-04-09 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabiDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(blank=True, verbose_name='何日目か(日付が変わった時のみ入力)')),
                ('time', models.CharField(max_length=8, verbose_name='時間 (例)9:00')),
                ('move', models.TextField(verbose_name='その時間の説明 (例)清水寺を訪問、拝観料400円、滞在時間1時間、見所...')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='スポットの写真(なくても可)')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabi.tabi', verbose_name='紐ずく旅')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='本文')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabi.tabi', verbose_name='どの記事へのコメントか')),
            ],
        ),
    ]
