# Generated by Django 4.2 on 2023-04-09 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabi', '0002_tabidate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabi',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='related_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
