# Generated by Django 4.2 on 2023-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabi', '0005_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ManyToManyField(blank=True, to='tabi.tabi', verbose_name='お気に入りの場所')),
            ],
        ),
    ]
