# Generated by Django 4.2 on 2023-04-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabi', '0006_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
