# Generated by Django 4.2 on 2023-04-14 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabi', '0008_connection_followings_remove_connection_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='followings',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='username',
        ),
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
